### ISSUE TITLE
有时候在抓取日志的时候报错中断，此现象出现的概率还比较大

### ISSUE THREAD

**Issue by nukupanda** [HAIMACloud/HMperf#5]
使用版本v1.0.0

```
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock countfatal: morestack on g0
SIGSEGV: segmentation violation
PC=0x7674c m=3 sigcode=1

goroutine 0 [idle]:
runtime.abort()
/usr/local/go/src/runtime/asm_arm.s:775 +0x4
runtime.write(...)
/usr/local/go/src/runtime/time_nofake.go:27
runtime.badmorestackg0()
/usr/local/go/src/runtime/proc.go:500 +0x28
runtime: unexpected return pc for runtime.gwrite called from 0x1c9e31
stack: frame={sp:0xc5e3ac, fp:0xc5e3c8} stack=[0xc5e000,0xc60000)
0x00c5e32c:  0x00000000  0x00000000  0x00000000  0x00000000 
0x00c5e33c:  0x00000000  0x00000000  0x00000000  0x00000000 
0x00c5e34c:  0x00000000  0x00000000  0x00000000  0x00000000 
0x00c5e35c:  0x00000000  0x00000000  0x00000000  0x00000000 
0x00c5e36c:  0x00000000  0x00000000  0x00000000  0x00000000 
0x00c5e37c:  0x00000000  0x00000000  0x00074d08 <runtime.morestack+0x00000014>  0x00000002 
0x00c5e38c:  0x001c89f4  0x00000017  0x00000017  0x0004743c <runtime.gwrite+0x00000034> 
0x00c5e39c:  0x0004724c <runtime.recordForPanic+0x00000044>  0x002ee33e  0x0004743c <runtime.gwrite+0x00000034>  0x002ee158 
0x00c5e3ac: <0x001c9e31  0x00047ce8 <runtime.printstring+0x00000060>  0x001d0b88  0x00000001 
0x00c5e3bc:  0x00000001  0x00000002  0x001c9e17 >0x0000001b 
0x00c5e3cc:  0x00047570 <runtime.printnl+0x00000024>  0x001d0b88  0x00000001  0x00000001 
0x00c5e3dc:  0x001d0b88  0x00000001  0x001d0b88  0x00000001 
0x00c5e3ec:  0x00000001  0x000457c8 <runtime.throw.func1+0x00000050>  0x001d0b88  0x00000001 
0x00c5e3fc:  0x00045744 <runtime.throw+0x00000040>  0x001c9e17  0x0000001b  0x0000001b 
0x00c5e40c:  0x001c9e17  0x0001a4e8 <runtime.unlock2+0x000000c0>  0x00c5e418  0x00045778 <runtime.throw.func1+0x00000000> 
0x00c5e41c:  0x001c9e17  0x0000001b  0x000473f0 <runtime.printunlock+0x00000040>  0x001c9e17 
0x00c5e42c:  0x0000001b  0x00000000  0x00000001  0x00000001
0x00c5e43c:  0x000457cc <runtime.throw.func1+0x00000054>  0x002ed6e0  0x00045744 <runtime.throw+0x00000040> 
runtime.gwrite({0x47570, 0x1d0b88, 0x1})
/usr/local/go/src/runtime/print.go:90 +0x34

goroutine 37 [running]:
runtime.systemstack_switch()
/usr/local/go/src/runtime/asm_arm.s:275 +0x4 fp=0xc97d50 sp=0xc97d4c pc=0x74c54
runtime.throw({0x1c9543, 0x19})
/usr/local/go/src/runtime/panic.go:1191 +0x40 fp=0xc97d64 sp=0xc97d50 pc=0x45744
runtime.lock2(0xcb3af0)
/usr/local/go/src/runtime/lock_futex.go:55 +0x21c fp=0xc97d90 sp=0xc97d64 pc=0x1a3e0
runtime.lockWithRank(...)
/usr/local/go/src/runtime/lockrank_off.go:23
runtime.lock(...)
/usr/local/go/src/runtime/lock_futex.go:48
runtime.chanrecv(0xcb3ac0, 0xc97e24, 0x1)
/usr/local/go/src/runtime/chan.go:508 +0x144 fp=0xc97ddc sp=0xc97d90 pc=0x1571c
runtime.chanrecv1(0xcb3ac0, 0xc97e24)
/usr/local/go/src/runtime/chan.go:439 +0x20 fp=0xc97df0 sp=0xc97ddc pc=0x155a8
os/exec.(*Cmd).Wait(0x10c6790)
/usr/local/go/src/os/exec/exec.go:518 +0x1a8 fp=0xc97e2c sp=0xc97df0 pc=0xed818
os/exec.(*Cmd).Run(0x10c6790)
/usr/local/go/src/os/exec/exec.go:341 +0x48 fp=0xc97e3c sp=0xc97e2c pc=0xeccb4
os/exec.(*Cmd).CombinedOutput(0x10c6790)
/usr/local/go/src/os/exec/exec.go:570 +0x98 fp=0xc97e50 sp=0xc97e3c pc=0xed9d8
romstat/stat/utils.(*AndroidShell).RunShell(0xc9e620, {0x1ca531, 0x1d})
/home/test/HMperf-HMperf/go_romstat/stat/utils/shell.go:37 +0x1c0 fp=0xc97e94 sp=0xc97e50 pc=0x186570
romstat/stat/plugins.(*SfLatencyStatPlugin).getTopSurfaceView(0xce6300)
/home/test/HMperf-HMperf/go_romstat/stat/plugins/sf_latency.go:60 +0x1ec fp=0xc97f1c sp=0xc97e94 pc=0x187ea4
romstat/stat/plugins.(*SfLatencyStatPlugin).runCollectThread(0xce6300)
/home/test/HMperf-HMperf/go_romstat/stat/plugins/sf_latency.go:203 +0x30 fp=0xc97fb4 sp=0xc97f1c pc=0x189544
romstat/stat/plugins.(*SfLatencyStatPlugin).runCollectThread-fm()
/home/test/HMperf-HMperf/go_romstat/stat/plugins/sf_latency.go:201 +0x28 fp=0xc97fbc sp=0xc97fb4 pc=0x18b34c
romstat/stat/utils.SetTimerMilliSecond(0xc8, 0xe1e058)
/home/test/HMperf-HMperf/go_romstat/stat/utils/timer.go:20 +0x68 fp=0xc97fe4 sp=0xc97fbc pc=0x186f60
runtime.goexit()
/usr/local/go/src/runtime/asm_arm.s:838 +0x4 fp=0xc97fe4 sp=0xc97fe4 pc=0x767ec
created by romstat/stat/plugins.(*SfLatencyStatPlugin).Run
/home/test/HMperf-HMperf/go_romstat/stat/plugins/sf_latency.go:290 +0x70

goroutine 1 [chan receive, 1 minutes]:
main.main()
/home/test/HMperf-HMperf/go_romstat/main.go:54 +0x4b4

goroutine 19 [syscall, 1 minutes]:
os/signal.signal_recv()
/usr/local/go/src/runtime/sigqueue.go:169 +0xf0
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:24 +0x14
created by os/signal.Notify.func1.1
/usr/local/go/src/os/signal/signal.go:151 +0x30

goroutine 33 [chan receive]:
romstat/stat.(*PluginManager).Start(0xce8120, 0x1)
/home/test/HMperf-HMperf/go_romstat/stat/stat.go:142 +0x160
created by main.main
/home/test/HMperf-HMperf/go_romstat/main.go:51 +0x490

goroutine 34 [select]:
github.com/shirou/gopsutil/internal/common.Sleep({0x1fd6b4, 0xcb8010}, 0x3b9aca00)
/root/go/pkg/mod/github.com/shirou/gopsutil@v2.21.11+incompatible/internal/common/sleep.go:12 +0x9c
github.com/shirou/gopsutil/cpu.PercentWithContext({0x1fd6b4, 0xcb8010}, 0x3b9aca00, 0x0)
/root/go/pkg/mod/github.com/shirou/gopsutil@v2.21.11+incompatible/cpu/cpu.go:152 +0xbc
github.com/shirou/gopsutil/cpu.Percent(...)
/root/go/pkg/mod/github.com/shirou/gopsutil@v2.21.11+incompatible/cpu/cpu.go:138
romstat/stat/plugins.(*SystemStatPlugin).cpuStat(0xce80f0)
/home/test/HMperf-HMperf/go_romstat/stat/plugins/system.go:52 +0xf0
created by romstat/stat/plugins.(*SystemStatPlugin).Run
/home/test/HMperf-HMperf/go_romstat/stat/plugins/system.go:90 +0x2c

goroutine 35 [sleep]:
time.Sleep(0x3b9aca00)
/usr/local/go/src/runtime/time.go:193 +0x170
romstat/stat/plugins.(*SystemStatPlugin).memStat(0xce80f0)
/home/test/HMperf-HMperf/go_romstat/stat/plugins/system.go:80 +0x128
created by romstat/stat/plugins.(*SystemStatPlugin).Run
/home/test/HMperf-HMperf/go_romstat/stat/plugins/system.go:91 +0x48

goroutine 36 [select]:
romstat/stat/plugins.(*SystemStatPlugin).Run.func1(0xce80f0)
/home/test/HMperf-HMperf/go_romstat/stat/plugins/system.go:94 +0x7c
created by romstat/stat/plugins.(*SystemStatPlugin).Run
/home/test/HMperf-HMperf/go_romstat/stat/plugins/system.go:92 +0x64

goroutine 38 [chan receive]:
romstat/stat/utils.SetTimer(0x1, 0xe1e070)
/home/test/HMperf-HMperf/go_romstat/stat/utils/timer.go:12 +0x7c
created by romstat/stat.(*PluginManager).Start
/home/test/HMperf-HMperf/go_romstat/stat/stat.go:133 +0xf0

trap    0x0
error   0x207
oldmask 0x0
r0      0x0
r1      0x1c89f4
r2      0x17
r3      0x4721c
r4      0xc820f0
r5      0x1
r6      0x1
r7      0x4
r8      0xc80000
r9      0x10
r10     0xc820f0
fp      0x2d697c
ip      0x74
sp      0xc5e398
lr      0x48ff4
pc      0x7674c
cpsr    0x60000010
fault   0x0



```

**Comment by haimachl** [comment]
这个错误感觉是golang本身的编译器的问题，尝试用新版本的golang，可能能解决此问题。
